FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
RUN npm install terser@^5.29.1
COPY frontend/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN chmod -R 755 /usr/share/nginx/html

RUN mkdir -p /etc/nginx/ssl  # Создаём директорию для сертификатов

EXPOSE 80 443  

CMD ["nginx", "-g", "daemon off;"]