# Generated by Django 4.2.20 on 2025-05-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
