# Generated by Django 4.2.20 on 2025-05-08 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0003_alter_transaction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('period_key', models.CharField(max_length=10)),
                ('income_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expense_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Period Summaries',
                'unique_together': {('user', 'period_type', 'period_key')},
            },
        ),
    ]
